# Generated by Django 5.1.5 on 2025-01-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_guidance',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
