# Generated by Django 5.1.5 on 2025-01-25 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='floorplan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='accessibility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='council_tax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='garden',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='size',
            field=models.CharField(blank=True, help_text='Size in sq feet', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_guidance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Brochures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brochure_url', models.URLField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brochures', to='properties.property')),
            ],
        ),
    ]
