# Generated by Django 5.1.5 on 2025-01-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_image_floorplan_property_accessibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tenure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.CharField(blank=True, null=True),
        ),
    ]
